---
abstract: 'Overrides the time() and sleep() core functions for testing'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 0
generated_by: 'Minilla/v3.1.18, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Time
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Test::Time:
    file: lib/Test/Time.pm
    version: '0.092'
requires:
  Test::More: '0'
resources:
  bugtracker: https://github.com/cho45/Test-Time/issues
  homepage: https://github.com/cho45/Test-Time
  repository: https://github.com/cho45/Test-Time.git
version: '0.092'
x_authority: cpan:SATOH
x_contributors:
  - 'Alexandr Ciornii <alexchorny@gmail.com>'
  - 'AnaTofuZ <anatofuz@gmail.com>'
  - 'Gianni Ceccarelli <gianni.ceccarelli@broadbean.com>'
  - 'Graham Knop <haarg@haarg.org>'
  - 'Michael Jemmeson <mjemmeson@cpan.org>'
  - 'minimalist <minimalist@lavabit.com>'
  - 'motemen <motemen@gmail.com>'
  - 'nanto_vi <nanto@moon.email.ne.jp>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
